# Generated by Django 2.1.3 on 2018-12-31 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CursoMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApellidoPaterno', models.CharField(max_length=60)),
                ('ApellidoMaterno', models.CharField(max_length=60)),
                ('Nombre', models.CharField(max_length=60)),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('FechaNacimiento', models.DateField()),
                ('TelefonoCasa', models.CharField(max_length=10)),
                ('TelefonoCelular', models.CharField(max_length=10)),
                ('CorreoEmpresarial', models.EmailField(max_length=60)),
                ('CorreoPersonal', models.EmailField(max_length=60)),
                ('Direccion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApellidoPaterno', models.CharField(max_length=60)),
                ('ApellidoMaterno', models.CharField(max_length=60)),
                ('Nombre', models.CharField(max_length=60)),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('FechaNacimiento', models.DateField()),
                ('CorreoPersonal', models.EmailField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CursoMateria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.CursoMateria')),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Codigo', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Pariente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApellidoPaterno', models.CharField(max_length=60)),
                ('ApellidoMaterno', models.CharField(max_length=60)),
                ('Nombre', models.CharField(max_length=60)),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('FechaNacimiento', models.DateField()),
                ('TelefonoCasa', models.CharField(max_length=10)),
                ('TelefonoCelular', models.CharField(max_length=10)),
                ('CorreoEmpresarial', models.EmailField(max_length=60)),
                ('CorreoPersonal', models.EmailField(max_length=60)),
                ('Direccion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=16)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='Periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Periodo'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='PADRE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Pariente'),
        ),
        migrations.AddField(
            model_name='cursomateria',
            name='iddocente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Docente'),
        ),
        migrations.AddField(
            model_name='cursomateria',
            name='idmateria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Materia'),
        ),
        migrations.AddField(
            model_name='curso',
            name='Nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nivel', to='GestionAcademica.Nivel'),
        ),
        migrations.AddField(
            model_name='curso',
            name='Seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seccion', to='GestionAcademica.Seccion'),
        ),
    ]
