# Generated by Django 2.1.3 on 2019-01-05 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('I', 'Inicial'), ('P', 'Primaria'), ('S', 'Secundaria')], default='P', max_length=1)),
                ('seccion', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CursoMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=60)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('direccion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidoPaterno', models.CharField(max_length=60)),
                ('apellidoMaterno', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=60)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('fechaNacimiento', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursoMateria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.CursoMateria')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Pariente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=60)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('direccion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=16)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Periodo'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Pariente'),
        ),
        migrations.AddField(
            model_name='cursomateria',
            name='iddocente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Docente'),
        ),
        migrations.AddField(
            model_name='cursomateria',
            name='idmateria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Materia'),
        ),
    ]
