# Generated by Django 2.1.3 on 2018-12-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0002_remove_curso_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='Seccion',
            field=models.ManyToManyField(to='GestionAcademica.Seccion'),
        ),
    ]
