# Generated by Django 2.1.3 on 2018-12-08 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0003_curso_seccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='Seccion',
        ),
        migrations.AddField(
            model_name='curso',
            name='Seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Seccion'),
        ),
    ]
