# Generated by Django 2.1.3 on 2018-12-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0004_auto_20181208_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApellidoPaterno', models.CharField(max_length=60)),
                ('ApellidoMaterno', models.CharField(max_length=60)),
                ('Nombre', models.CharField(max_length=60)),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('FechaNacimiento', models.DateField()),
                ('TelefonoCasa', models.IntegerField(max_length=10)),
                ('TelefonoCelular', models.IntegerField(max_length=10)),
                ('CorreoEmpresarial', models.CharField(max_length=60)),
                ('CorreoPersonal', models.CharField(max_length=60)),
                ('Direccion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Pariente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApellidoPaterno', models.CharField(max_length=60)),
                ('ApellidoMaterno', models.CharField(max_length=60)),
                ('Nombre', models.CharField(max_length=60)),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('FechaNacimiento', models.DateField()),
                ('TelefonoCasa', models.IntegerField(max_length=10)),
                ('TelefonoCelular', models.IntegerField(max_length=10)),
                ('CorreoEmpresarial', models.CharField(max_length=60)),
                ('CorreoPersonal', models.CharField(max_length=60)),
                ('Direccion', models.CharField(max_length=120)),
            ],
        ),
    ]
