# Generated by Django 2.1.3 on 2018-12-08 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0005_docente_pariente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApellidoPaterno', models.CharField(max_length=60)),
                ('ApellidoMaterno', models.CharField(max_length=60)),
                ('Nombre', models.CharField(max_length=60)),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('FechaNacimiento', models.DateField()),
                ('CorreoPersonal', models.EmailField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='docente',
            name='CorreoEmpresarial',
            field=models.EmailField(max_length=60),
        ),
        migrations.AlterField(
            model_name='docente',
            name='CorreoPersonal',
            field=models.EmailField(max_length=60),
        ),
        migrations.AlterField(
            model_name='pariente',
            name='CorreoEmpresarial',
            field=models.EmailField(max_length=60),
        ),
        migrations.AlterField(
            model_name='pariente',
            name='CorreoPersonal',
            field=models.EmailField(max_length=60),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='PADRE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GestionAcademica.Pariente'),
        ),
    ]
