# Generated by Django 2.1.3 on 2018-12-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0007_materia_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='TelefonoCasa',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='docente',
            name='TelefonoCelular',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pariente',
            name='TelefonoCasa',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pariente',
            name='TelefonoCelular',
            field=models.CharField(max_length=10),
        ),
    ]
